Floorp-Projects/Floorp

browser/themes/shared/browser.inc.css

Fix urlbar style

---

browser/themes/shared/browser.inc.css
browser/themes/shared/tabs.inc.css

マテリアルテーマのバグ修正

---

browser/themes/addons/motion/userChrome.css

**「垂直タブに Floorp を最適化」テーマを有効化時に、垂直タブを右側に移動させた時の開閉に対応しました。**
閉
開

「垂直タブに Floorp を最適化」テーマを有効化時に垂直タブを右側に移動させた時の開閉に対応

---

browser/locales/en-US/browser/preferences/preferences.ftl

This commit makes "normal mode" and "classic menu button" uppercased

Uppercase remaining modes from "Tab Bar Settings"

---

browser/components/aboutcontributor/contributor.html

This commit improves code and design of the about:contributors tab
Before:
After:

Improve about:contributors tab

---

.github/workflows/linux-build-aarch64.yml

Added Linux AArch64 build workflow.
It supports 64bit arm devices such as Raspberry Pi.
Modified Linux x64 workflow file for arm cross-compilation.
This is my first pull request so I apologize if I did something wrong.

Add Linux AArch64 build

---

browser/components/preferences/main.inc.xhtml
browser/components/preferences/preferences.js
browser/components/preferences/preferences.xhtml
floorp/browser/app/profile/000-floorp.js
floorp/browser/base/content/browser-command.js
floorp/browser/base/content/browser-floorp.css
floorp/browser/base/content/browser-manager-sidebar.js
floorp/browser/base/content/browser-webpanel.inc.xhtml
floorp/browser/components/preferences/bsb.inc.xhtml
floorp/browser/components/preferences/bsb.js
floorp/browser/components/preferences/dialogs/customURLs.js
floorp/browser/components/preferences/dialogs/customURLs.xhtml
floorp/browser/components/preferences/floorp-main.js
floorp/browser/components/preferences/jar.mn
floorp/browser/components/preferences/lepton.js
floorp/browser/components/preferences/preferences-floorp.css
floorp/browser/extensions/webextensions/webpanel-ua/APIs/webRequestExt.js
floorp/browser/locales/en-US/floorp.ftl

- 大量にあったPrefを一つにまとめてObject化
- ついでに無限に登録できるように
- ブラウザ内蔵のページも登録したり削除したりできるように
- それに合わせ設定画面を変更
- ウェブパネルの幅のグローバル値を設定から変更可能に
ざっとこんな感じですかね(何やったか全てはおぼえてないかも)  
<br>
あと、Prefのアップデートは`floorp/browser/base/content/browser-manager-sidebar.js`の6行目にあると思います  
今は`floorp.browser.sidebar2.customurl2`(3つめのウェブパネル)に何かしらのURLが登録されているとき、Objectが初期値ならObjectに変換してPrefを削除、そうでなければなにもせずPrefを削除って感じになってます  
要改善な気がします  
<br>
最後に、設定画面いじる時に若干他のところにも手を出しちゃいました
馬鹿です。どうも。

Browser Manager Sidebar

---

floorp/browser/base/content/browser-userChrome.js
floorp/browser/extensions/userChromejs/chromecss.uc.js

macでChromeCSSを使えるようにしてきました
(といっても、逆にMacでできなかったのはアクセス権のあるフォルダ作成のみですが)
あと、mac標準のテキストエディタはなぜか使えません
Firefox標準の方でも使えません
なので、VSCodeでデバッグしてます

ChromeCSS in macOS

---

floorp/browser/components/BrowserManagerSidebar.jsm
floorp/browser/extensions/webextensions/floorp-actions/background.js
floorp/browser/extensions/webextensions/floorp-system/shared/gesturefy/gesturefy.js

- BMSのTSTは、強制削除にしておきました(BMSに拡張機能のサイドバーを使えるような設定をつくったらそっちに移行するかも)
- Gesturefyは、TSTが導入されたらすぐ動くように、機能だけは残しときました
- 「ツリー型タブを開く」Gesturefyのコマンドは、そのジェスチャーの設定を開いた時点で「サイドバーで選択したアドオンを開く」に置き換えられるようにしました

[FB] Cope with deleting TST

---

floorp/browser/app/profile/000-floorp.js
image/DecoderFactory.cpp
image/decoders/nsJXLDecoder.cpp
image/decoders/nsJXLDecoder.h
modules/libpref/init/StaticPrefList.yaml
toolkit/moz.configure
uriloader/exthandler/nsExternalHelperAppService.cpp

Testcases:
https://jpegxl.info/test-page/ (main test, with animations, transparency, and ICC)
https://google.github.io/attention-center/ (progressive decoding test)
Based on the following patches:
* [D119700](https://phabricator.services.mozilla.com/D119700), intended for [bug 1709814](https://bugzilla.mozilla.org/show_bug.cgi?id=1709814)
* [D122158](https://phabricator.services.mozilla.com/D122158), intended for bugs [1709818](https://bugzilla.mozilla.org/show_bug.cgi?id=1709818) and [1709816](https://bugzilla.mozilla.org/show_bug.cgi?id=1709816)
* [D122159](https://phabricator.services.mozilla.com/D122159), intended for [bug 1709815](https://bugzilla.mozilla.org/show_bug.cgi?id=1709815)
* Unified XUL Platform (a fork of mozilla-esr52) commit …

Expand JPEG XL support

---

floorp/browser/base/content/browser-chromeCSS.js
floorp/browser/themes/designs/floorp-legacy/test_legacy.css

ChromeCSSの  
- Floorpを再起動すると有効無効が逆転する  
- Floorp初期起動の時に多分rebuildがうまくいかない  
Fluerialの  
- 垂直タブの固定タブが昔のように横に詰める前提になってた  
- ワークスペースアイコンが悲惨なことになってた    
を修正してきました

Fix a lot of bugs

---

floorp/browser/base/content/browser-verticaltabs.css

---
`--lwt-accent-color` has changed correctly when it is lw-theme, so it has been changed.
(There is a problem when the system defalt theme)
Before:
After:
This is tested with linux.

 [FB] Verticaltab | Fix background color

---

browser/installer/windows/moz.build

---
Windowsの設定で表示されるバージョンをFloorpのバージョンに修正しました
Before:
After:
あと`./mach package`で生成されるファイルの名前もFloorpのバージョンになってます(他にも変わってる所あるかも?)
ESR102の
https://github.com/Floorp-Projects/Floorp/commit/e58357add948f63660c690bf68dcca6b44d8769a
https://github.com/Floorp-Projects/Floorp/commit/2376a412318bfaf6420d8b655a86257a545a42ac
のコミットから取ってきました

[FB] Installer | Fix Display Version

---

.github/workflows/linux-x64-deb.yml

Giving execute permissions to GLXTest and VAAPITest to enable WebGL in Linux. (This will only affect .deb)
---
https://github.com/Floorp-Projects/Floorp/issues/351
I think this will resolve this issue↑
Maybe this needs testing before applying to workflows.

Update linux-x64-deb.yml to Enable WebGL

---

README.md
js/src/jit/arm64/vixl/MozCpu-vixl.cpp

---
日本語
ShinecatのREADMEを作るために確認していたら偶然発見した謎のアーキテクチャ**AAArch64**。  
Googleで検索しても修正したと言われ、Wikipedia(ja)には記事がないし、Wikipedia(en)には歴史にこそ記載されているものの、リンクもなくましてやAArch64の事を触れていた。  
そのため`AAArch64`について、衍字として修正を行った。  
リポジトリ内の修正点は二カ所であった。
**READMEおよびビルドに関係のないコメントの編集のため、テストをスキップしています。**
---
English
A mysterious architecture **AAArch64** that I discovered by accident when checking to create a README for Shinecat.  
A Google search showed that it had been modified, Wikipedia (en) has no article on it, and Wikipedia (en), although it is mentioned in the history, has no link to it, much less the content which should originally be "AArch64".  
The `AAArch64` has therefore been corrected as a typographical error.  
There were two corrections in the repository.
**Skipped testing due to edits to the README and …

【衍字修正(Error correction)】AAArch64

---

browser/branding/official/locales/en-US/brand.ftl

It sounds way more natural and professional without the 'the'.
---

Grammar fix for the about string

---

README.md

- [ /] Referenced all related issues
- [ /] Have tested the modifications
---
As per pinned comment https://aur.archlinux.org/packages/floorp#comment-952359 floorp-bin should now be used.

README - updated AUR link to point to floorp-bin

---

.github/workflows/linux-build.yml

use find command instead of ls-grep-awk chain
add double quote to the path
---

[FB] Worksflows | skip 'assets' dir

---

.github/workflows/auto-labeler-to-issues.yml
.github/workflows/daily-build-with-update.yml
.github/workflows/deployments.yml
.github/workflows/linux-build.yml
.github/workflows/linux-x64-deb.yml
.github/workflows/macOS-Universal.yml
.github/workflows/macOS-generate-profile-data-and-jarlog.yml
.github/workflows/macOS-integration.yml
.github/workflows/update-submodule.yml
.github/workflows/window-generate-profile-data-and-jarlog.yml
.github/workflows/windows-build.yml

---
node16を使用するactionを使用すると実行時に警告が出るようになったため、使用しているactionのバージョンを更新しました
ついでにインデントが変なところとかを修正したり
テストはしてない(おい)んですが、各actionのchangelogを見た感じは大丈夫そう
softprops/action-gh-release と apple-actions/import-codesign-certs はnode16を使用していますが、
node20を使用するバージョンが出ていないため更新できていません
(softprops/action-gh-release はnode20にするコミットはされているのでコミットSHAを指定して回避することもできますが...)

[FB] Workflow | Update action version

---

README.md

firefox-gnome-theme's both license and repo links were linked to license

---

.gitignore
python/mach/mach/config.py

---
Basically the `RawConfigParser` might've changed. 
I was cleaning my env for my features for Floorp and when I started from scratch this was the result:
~It was an easy fix, just changing what python suggested.~
I fixed it to follow mozilla's upstream, now everything works.

Error with `config.py` for any `./mach` operation

---

browser/components/BrowserContentHandler.sys.mjs
browser/installer/windows/msix/AppxManifest.xml.in
browser/installer/windows/nsis/shared.nsh
browser/installer/windows/nsis/uninstaller.nsi
image/DecoderFactory.cpp
image/decoders/nsJXLDecoder.cpp
image/decoders/nsJXLDecoder.h
modules/libpref/init/StaticPrefList.yaml
toolkit/components/downloads/DownloadList.sys.mjs
toolkit/components/extensions/parent/ext-downloads.js
toolkit/content/filepicker.properties
toolkit/moz.configure
widget/gtk/nsAppShell.cpp

Adds back proper JPEG XL support similar to https://github.com/Floorp-Projects/Floorp/pull/268 but for ESR128 and also with the extra feature of expending what parts of the browser understand ".jxl" compared to the previous pull request.
tests:
https://jpegxl.info/test-page/ (main tests)
https://google.github.io/attention-center/ (progressive decoding)
https://web.archive.org/web/20240208234112id_/https://people.csail.mit.edu/ericchan/hdr/hdr-jxl.php (HDR photography)
patches in the first commit are sourced from:
https://phabricator.services.mozilla.com/D119700
https://phabricator.services.mozilla.com/D122158
https://phabricator.services.mozilla.com/D122159
https://bugzilla.mozilla.org/show_bug.cgi?id=1709814#c5

Bring back extended JPEG XL (JXL) image support for ESR128.

---

browser/components/preferences/privacy.inc.xhtml

---
from the preferences page, clicking "View this addon in addons.mozilla.org" for "Facebook Container" correctly detects users language, but for "uBlock Origin" its hardcoded language to `/ja/`

[FB] Preferences| Auto detect firefox add-on language (ublock)

---

src/apps/main/core/common/panel-sidebar/components/style.css

---
The sidebar is not hidden when fullscreen since the css rule uses the wrong id: #sidebar-select-box instead should be #panel-sidebar-select-box
https://github.com/Floorp-Projects/Floorp/blob/90692e3857f3eea0a2732bf3a629ad472b14df70/src/apps/main/core/common/panel-sidebar/components/style.css#L201

fix: Fix hiding sidebar when fullscreen

---

src/apps/main/core/common/undo-closed-tab/index.ts
src/apps/main/core/utils/browser-action.tsx

---
When using the undo closed tab widget within a second window, it instead undos the closed tab in the first window.
This fix uses the view provided by the XULCommandEvent to trigger the undo in the specific window the widget was clicked in.

Fix undo closed tab with multiple windows
