- browser/themes/shared/theme/floorp-legacy/test_legacy.css
> I don`t like bugs

- browser/extensions/floorp-system/macOS/manifest.json
- browser/extensions/floorp-system/windows/manifest.json
This commit fixes pop-up text in “Floorp System” (aka Floorp Updater) extension.
> Fix pop-up text in "Floorp System" extension

- .github/workflows/macOS-Universal.yml
- .github/workflows/windows-build.yml
> Add macOS Universal build & add some auto build scripts

- browser/components/aboutcontributor/contributor.html
- browser/locales/en-US/browser/preferences/preferences.ftl
This commit fixes several grammar mistakes in Floorp's preferences and the “contributor” section
> Fix several grammar mistakes in Floorp's preferences

- browser/app/profile/000-floorp.js
> Fix pref typo

- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/data/content/activity-stream.bundle.js
家の回線が弱かったりビルドしたり自分のgitの知識が甘すぎたりしてPRが遅れました。
レビューよろしくおねがいします。
> Remove darkreader

- browser/themes/shared/theme/floorp-legacy/test_legacy.css
> FIX Legacy PanelUI Button & ComboBox

- browser/themes/shared/preferences/privacy.css
> Make width of view-on-amo dependent on the size of it's content

- browser/locales/en-US/browser/preferences/preferences.ftl
This PR fixes grammar inside “how-to-disable-ntbg” label
> rephrase how-to-disable-ntbg in the preferences

- browser/locales/en-US/browser/preferences/preferences.ftl
This PR improves the description of some labels in the “trackingprotection” section
> improve locale in trackingprotection section

- browser/base/content/browser-preferences.js
This PR updates user agents to the latest available
> update useragents to the latest available

- browser/base/content/browser-command.js
- browser/base/content/browser-manager-sidebar.js
This PR reduces a lot of static code
> refactor part 1

- browser/components/preferences/dialogs/customURL.js
> Fix adding https to extension on the sidebar

- README.md
This PR refactors some parts of the README
> README: do some refactoring

- browser/base/content/browser-command.js
This commit reduces code in browser-command.js
> browser-command.js: do some cleaning

- browser/base/content/browser-command.js
- browser/base/content/browser-manager-sidebar.js
- browser/base/content/browser-webpanel.inc.xhtml
This commit reduces setters and makes calculation of the custom-url sidebars more dynamic.
Before merge, please, check if everything is ok
> browser-manager.js: unify setters and make sidebar more dynamic

- browser/app/profile/000-floorp.js
- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/content-src/components/Background/_Background.scss
- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/css/activity-stream-linux.css
- browser/components/newtab/css/activity-stream-mac.css
- browser/components/newtab/css/activity-stream-windows.css
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.inc.xhtml
- browser/components/preferences/home.js
- browser/locales/en-US/browser/preferences/preferences.ftl
Floorp Homeの背景画像の設定を改造してきました
- Unsplashの写真
- 8.xのグラデーション
- なし
の3つです  
(英語は直していただけるとありがたいです...)
> Floorp Home`s Background

- browser/base/content/browser-command.js
This PR makes sidebar calculation use const to calculate a webpanel ID.
> browser-command.js: get webpanel id using predefined const

- browser/locales/en-US/browser/menubar.ftl
- browser/locales/en-US/browser/preferences/preferences.ftl
> eng: fix some grammar

- browser/base/content/browser-command.js
- browser/base/content/browser-manager-sidebar.inc.xhtml
This PR reduces repeatable code related to the sidebar actions
> browser-command.js: unify sidebar actions

- browser/components/aboutcontributor/contributor.html
This PR adds two more people as contributors to the Floorp Project.
> maintainers: add new contributors

- floorp/browser/locales/en-US/floorp.ftl
This PR makes rest-mode label more descriptive
> localization: clarify rest-mode hotkey

- floorp/browser/locales/en-US/floorp.ftl
This PR removes unnecessary words from the lepton settings
> localization: improve lepton settings

- .github/mozconfig_win_pgo_base
- .github/setup-buildtool-windows-pgo.py
- .github/workflows/windows-build-with-pgo.yml
This improves performance for the Windows version.
Fixed #56
> Allows PGO to be used for automatic builds of the Windows version.

- floorp/browser/base/content/browser-command.js
- floorp/browser/base/content/browser-floorp.css
- floorp/browser/base/content/browser-manager-sidebar.js
- floorp/browser/base/content/browser-webpanel.inc.xhtml
- floorp/browser/components/preferences/bsb.inc.xhtml
- floorp/browser/components/preferences/bsb.js
- floorp/browser/components/preferences/dialogs/customURLs.js
- floorp/browser/components/preferences/dialogs/customURLs.xhtml
- floorp/browser/components/preferences/preferences-floorp.css
- floorp/browser/locales/en-US/floorp.ftl
- ドラッグアンドドロップで並び替え
- ウェブパネルを追加ボタン
- 右クリックからの、現在のページをサイドバーに追加
- 右クリックからの、リンク先のページをサイドバーに追加
(衝突しとるぅぅ...)
> Bsb infinity Part2

- floorp/browser/base/content/browser-command.js
- floorp/browser/base/content/browser-floorp.css
Changes
* Displays a different icon if the icon is being retrieved or if it fails to be retrieved.
* Make it easy to see that you have clicked on a button.
* When an add-on page is added, the add-on icon is now displayed.
* Fix the width of the icon to 16px.
> Fixed icon-related issues

- browser/components/preferences/main.inc.xhtml
- floorp/browser/base/content/browser-command.js
- floorp/browser/components/preferences/floorp-main.js
- floorp/browser/locales/en-US/floorp.ftl
> Fix problem with failure to obtain icons when accessed from China.

- floorp/browser/base/content/browser-startup.js
MacでuserChrome/Content.cssが自動生成されるようにしました
きっとWin/Linuxでもできるはず...
> [FB] File | Make the CSS file

- floorp/browser/base/content/browser-command.js
This PR starts to reduce amount of getdocumentbyid getters in browser-command.js
> browser-command.js: initiate getdocument getter reduction in browser-command.js

- floorp/browser/base/content/browser-command.js
> [FB] BMS | Fix icon url

- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/content-src/components/Background/_Background.scss
- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/css/activity-stream-linux.css
- browser/components/newtab/css/activity-stream-mac.css
- browser/components/newtab/css/activity-stream-windows.css
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.inc.xhtml
- browser/components/preferences/home.js
- floorp/browser/app/profile/000-floorp.js
- floorp/browser/components/FloorpStartup.jsm
- floorp/browser/components/preferences/preferences-floorp.css
- floorp/browser/locales/en-US/floorp.ftl
任意のフォルダ内の画像をFloorp Homeの背景として使えるようにしてきました
> [FB] Floorp Home | Use the Selected Images as Background

- floorp/browser/locales/en-US/floorp.ftl
This PR reworks locale of newtab-background images
> localization: improve newtab-images locale

- floorp/browser/base/content/browser-manager-sidebar.js
- floorp/browser/components/preferences/bsb.js
> [FB] BMS | Fix Bugs

- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.js
- floorp/browser/base/content/browser-manager-sidebar.js
- floorp/browser/components/FloorpStartup.jsm
- floorp/browser/components/preferences/bsb.js
とりあえず、chromeフォルダの中にnewtabImagesフォルダを作るようにしてきました
> [FB] about:newtab | Fix bugs

- floorp/browser/extensions/webextensions/floorp-system/shared/API/sidebar.js
- floorp/browser/extensions/webextensions/floorp-system/shared/API/sidebar.json
- floorp/browser/extensions/webextensions/floorp-system/shared/gesturefy/background.js
- floorp/browser/extensions/webextensions/floorp-system/shared/gesturefy/gesturefy.js
- floorp/browser/extensions/webextensions/floorp-system/shared/manifest.json
- floorp/browser/extensions/webextensions/floorp-system/shared/moz.build
- floorp/browser/locales/en-US/floorp.ftl
Gesturefyで指定したアドオンのサイドバーを開く機能を追加しました
(もう飛ばない！)
> [FB] Gesturefy | Add command

- .github/mozconfig_win_pgo_base
- .github/setup-buildtool-windows-pgo.py
- .github/workflows/daily-build.yml
- .github/workflows/windows-build-with-pgo.yml
> [FB] Workflow | Fix windows build

- .github/pull_request_template.md
> localization: fix grammar in PR template

- floorp/browser/base/content/browser-verticaltabs.js
- floorp/browser/locales/en-US/floorp.ftl
---
This PR removes unneeded getters from browser-verticaltab.js and rewrites locale of native-tabbar-tip
> browser-verticaltab: do some cleanup

- floorp/browser/locales/en-US/floorp.ftl
> localization: improve localization of some prefs

- floorp/browser/base/content/browser-statusbar.js
---
This PR reduces getters in browser-statusbar.js
> browser-statusbar.js: reduce getters

- floorp/browser/locales/en-US/floorp.ftl
---
This PR removes numerous obsolete strings/prefs, that were used in previous versions of Floorp Browser, but aren't being used right now.
> [FB] Localization | Remove obsolete strings

- floorp/browser/locales/en-US/floorp.ftl
> [FB] Localization | Remove obsolete strings, Modify some strings.

- floorp/browser/app/profile/000-floorp.js
- floorp/browser/base/content/browser-design.js
- floorp/browser/themes/designs/floorp-legacy/test_legacy.css
垂直タブ仕様時のFluerialについて色々改良を加えてきました
> [FB] Fluerial | Improve design when using vertical tabs

- floorp/browser/components/OpenLinkInExternal.jsm
> After 10.12.0

- floorp/browser/base/content/browser-toolbar-features.js
---
This PR improves the code of the clock widget
> [FB] Widgets | Improve clock widget

- floorp/browser/base/content/browser-manager-sidebar.js
- floorp/browser/base/content/browser-tabbar.js
---
This PR improves the code of some functions
> [FB] Codebase | Refactor some functions

- floorp/browser/locales/en-US/floorp.ftl
---
This PR improves the naming of some prefs.
> [FB] Localization | Improve some prefs

- .github/mozconfig_win_pgo_base
- .github/setup-buildtool-windows-pgo.py
> [FB] Workflow | fix build error

- .github/workflows/linux-build-flatpak.yml
> [FB] Workflow | Lightened the build of the Flatpak version.

- browser/components/newtab/common/Actions.jsm
- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/content-src/components/CustomizeMenu/_CustomizeMenu.scss
- browser/components/newtab/content-src/components/TopSites/_TopSites.scss
- browser/components/newtab/css/activity-stream-linux.css
- browser/components/newtab/css/activity-stream-mac.css
- browser/components/newtab/css/activity-stream-windows.css
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.inc.xhtml
- browser/components/preferences/home.js
- floorp/browser/app/profile/000-floorp.js
- floorp/browser/locales/en-US/floorp.ftl
- 440とかいうファイル数の画像でも正常に新しいタブが機能するようにしました
- 新しいタブの画像を一番最初にすべて読み込むことをやめました
- blur効果を無効にできるようにしました
> [FB] about:newtab | Fix bugs and improve

- .github/workflows/linux-build-aarch64.yml
- .github/workflows/linux-build-x64-deb-noppa.yml
- .github/workflows/linux-build-x64-deb.yml
- .github/workflows/linux-build-x64.yml
- .github/workflows/windows-build-with-pgo.yml
Change build machine. It should be merged just before the build
> [FB] Workflow | Relpace Ubuntu-latest with Buildjet

- .github/workflows/linux-build-aarch64.yml
- .github/workflows/linux-build-x64-deb-noppa.yml
- .github/workflows/linux-build-x64-deb.yml
- .github/workflows/linux-build-x64.yml
- .github/workflows/windows-build-with-pgo.yml
> [FB] Workflow | Make workflow working on forks.

- floorp/browser/components/preferences/bsb.js
- floorp/browser/components/preferences/preferences-floorp.css
BMSの設定画面のリストに上下ボタンを追加しました
D&D以外の並び替え機能となります
(実はタッチパネルでは並び替えができない可能性があった)
> [FB] about:preferences | Improve BMS's setting

- .github/workflows/linux-build-flatpak.yml
> [FB] Workflow(Flatpak aarch64) | Using GHA cache.

- floorp/browser/locales/en-US/floorp.ftl
---
This PR improves and reworks localisation in Floorp.
> [FB] Localisation | Improve localisation

- README.md
---
This PR rewrites README to make it look better.
> [FB] README | Improve README

- floorp/browser/locales/en-US/floorp.ftl
---
A few more adjustments for en_US as I missed a few strings on my initial look-throughs and also thought of better strings for some of the already changed strings.
Additionally provides extra fixes for referenced softwares' names and fixes a minor name inconsistency in a string compared to nearby strings.
> Some more en_US adjustments

- browser/components/preferences/preferences.xhtml
- floorp/browser/base/jar.mn
- floorp/browser/components/preferences/csk.inc.xhtml
- floorp/browser/components/preferences/csk.js
- floorp/browser/components/preferences/preferences-floorp.css
- floorp/browser/locales/en-US/floorp.ftl
> [FB] Custom Keyboard Shortcut | Enable Preferences

- floorp/browser/components/notes/content/notes-bms.css
- floorp/browser/components/notes/content/notes-bms.html
- floorp/browser/components/notes/content/notes.js
---
どのノートを選択しているかわかりやすくしたりしました
https://github.com/Floorp-Projects/Floorp/assets/87810571/d9d94064-4051-4956-b21c-48a9916456fd
> Notes UI Enhancement

- floorp/browser/base/content/browser-command.js
- floorp/browser/base/content/browser-context-menu.js
- floorp/browser/base/content/browser-design.js
- floorp/browser/base/content/browser-downloadbar.js
- floorp/browser/base/content/browser-favicon-color.js
- floorp/browser/base/content/browser-pinned-tabs-title.js
- floorp/browser/base/content/browser-preferences.js
- floorp/browser/base/content/browser-rest-mode.js
- floorp/browser/base/content/browser-statusbar.js
- floorp/browser/base/content/browser-tabbar.js
- floorp/browser/base/content/browser-toolbar-features.js
- floorp/browser/base/content/browser-verticaltabs.js
- floorp/browser/components/preferences/floorp-privacy.js
- floorp/browser/components/preferences/workspaces.js
---
Improve syntax of Floorp's source code and refactor some functions.
> [FB] Refactor | Refactor

- floorp/browser/components/about/aboutcontributors/contributors.html
---
This isn't meant to be narcissistic in any way, more-so that I just only realised now that this page exists, so followed the page's advice and made this Pull Request to add myself (I would add anyone else whose missing, but I don't know where to start looking for other missing people).
I would've put myself in localisers but given the fact I've also contributed a bugfix (and will likely contribute more bugfixes in the future) I decided to put myself under the other contributors section instead.
PS: Could this maybe be automated somehow with a GitHub Actions process of some kind?
> Added myself to contributors

- README.md
---
Fix every possible grammar mistake in README.
> [FB] README | Fix every possible grammar mistake

- floorp/browser/themes/designs/lepton/leptonChrome.css
- floorp/browser/themes/designs/lepton/photonChrome-multitab.css
---
Fixed folder icons not showing up in 'Open Profile Directory' in application menu.
I'm an amateur, so I may have missed some points to fix.
> Fix: Folder icons in 'Open Profile Directory' in application menu

- README.md
---
This PR updates link to English localization
> [FB] README | Add link to the new English repo

- browser/components/preferences/main.inc.xhtml
- floorp/browser/app/profile/000-floorp.js
- floorp/browser/components/preferences/floorp-main.js
> [FB] Portable | Update Portable Preference

- .github/workflows/linux-build.yml
> [FB] Workflow | Use mold linker in linux build

- .github/workflows/linux-build.yml
Reverts Floorp-Projects/Floorp#469
> Revert "[FB] Workflow | Use mold linker in linux build"

- .github/ISSUE_TEMPLATE/bug_report.yml
> [FB] Templates | Fix grammar

- README.md
---
Add the now-upstream Nix(OS) package for Floorp, which has been merged a few days ago.
This of course still will take a bit of time to trickle into the unstable and stable branches, but it's there nonetheless.
> [FB] README | Add NixOS package

- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/content-src/components/Background/_Background.scss
- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/css/activity-stream-linux.css
- browser/components/newtab/css/activity-stream-mac.css
- browser/components/newtab/css/activity-stream-windows.css
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.inc.xhtml
- browser/components/preferences/home.js
新しいタブでたくさんの画像を選べるように(コンフリクトぉ...)
> 2023 12 10

- README.md
---
Fixed wrong invite link to discord server.
> [FB] Readme | Fix broken discord link

- README.md
> [FB] Readme | Fix broken download and install link

- .github/workflow.md
---
The translation was made using Google Translate. Please check, if it is correct. I have nearly no knowledge of Japanese.
> Translated arguments from Japanese to English in workflow.md

- browser/base/content/tabbrowser.js
- browser/components/BrowserGlue.sys.mjs
- browser/components/preferences/preferences.js
- browser/components/sessionstore/SessionStore.sys.mjs
- browser/components/sessionstore/TabState.sys.mjs
> [FB] Dev | feat/fast-debug

- .github/ISSUE_TEMPLATE/bug_report.yml
> [FB] Issues | Rework issue template

- browser/base/content/tabbrowser-tabs.js
> [FB] Code  | Fix typos

- browser/base/content/tabbrowser-tabs.js
> [FB] Code | Fix more typos

- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/newtab/content-src/components/Base/_Base.scss
- browser/components/newtab/css/activity-stream-linux.css
- browser/components/newtab/css/activity-stream-mac.css
- browser/components/newtab/css/activity-stream-windows.css
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/newtab/lib/PrefsFeed.jsm
- browser/components/preferences/home.inc.xhtml
- browser/components/preferences/home.js
> [FB] Floorp Home | Add option to hide support and image credit links in the newtab page

- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/preferences/home.js
---
Fixes #619 
Also made a few eslint formatting changes in `Background.jsx`.
> [FB] Floorp Home | Fix custom background not showing up at startup

- .github/workflows/linux-x64-deb.yml
> fix mkdir paths

- browser/components/newtab/content-src/components/Background/Background.jsx
- browser/components/newtab/data/content/activity-stream.bundle.js
- browser/components/preferences/home.js
Reverts Floorp-Projects/Floorp#885
> Revert "[FB] Floorp Home | Fix custom background not showing up at startup"

- browser/components/about/AboutRedirector.cpp
- browser/components/about/components.conf
- browser/components/extensions/schemas/chrome_settings_overrides.json
- browser/components/urlbar/UrlbarController.sys.mjs
- caps/nsScriptSecurityManager.cpp
- docshell/base/URIFixup.sys.mjs
- toolkit/components/extensions/Schemas.sys.mjs
- toolkit/components/search/SearchEngine.sys.mjs
- toolkit/components/search/SearchService.sys.mjs
> Implemet Prototype level Floorp Search Engine

- README.md
---
Adds homebrew install command in README.md
> Adds homebrew install command for mac

- README.md
---
Changed "build" to "built" (the past tense) which is correct.
> Fixed grammatical error in README.md

- .github/workflows/daily-build-with-update.yml
- .github/workflows/deployments.yml
- .github/workflows/macOS-integration.yml
---
#938 時点でnode20を使用する新しいバージョンが出てなかった分の更新
見た感じnode20への移行以外の破壊的変更はなさそう
> [FB] Workflow | Update action version

- browser/base/content/navigator-toolbox.inc.xhtml
- browser/components/newtab/content-src/components/Base/Base.jsx
- browser/components/preferences/preferences.xhtml
- toolkit/mozapps/extensions/content/aboutaddons.html
> [FB] | Replace HardCode Text

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
---
#1200 #1184  を解決 (したい)
- I have ~~tried to create~~ **checked with** a new profile and the issue still occurs.
- I have checked this problem is not ~~ocurring~~ **occurring** in the latest version of Firefox ESR.
- ~~All~~ **Most** Linux Distributions
glibc 諸々は Firefox ESR のシステム要件に書いてありますので、README への記載は不要であると判断しました。
> [FB] README | Correct bug_report and README

- README.md
---
システム要件を ESR128 に合わせたものに更新しました。
ソース: https://www.mozilla.org/en-US/firefox/128.0esr/system-requirements/
> [FB] README | Update System Requirements

- browser/components/preferences/privacy.inc.xhtml
---
Fixes https://github.com/Floorp-Projects/Floorp/issues/1370
Requires https://github.com/Floorp-Projects/Unified-l10n-central/pull/77
Previous:
With this PR:
> fix: Fix RFP checkbox

- README.md
> Add SlackBuilds.org for Slackware based Distributions

- build/moz.build
Update Floorp Update Repository URL from `floorp-update.ablaze.one` to `updates.floorp.app`
---
> Update Floorp Update Repository URL 

- .github/workflows/publish_release.yml
> Implement Update files section for RC Channel
